platform :ios, ‘8.0’

target ‘LearnLife’ do
    
    pod 'EasyIOS', :git => 'https://github.com/zhuchaowe/EasyIOS.git', :commit => '900be0c90c5e24e715293ce8dff04b35bbae3e74'
    pod 'pop', '1.0.9'
    pod 'XAspect', '1.0.5'
    #pod 'VTMagic'
    pod 'RETableViewManager', '1.7'
    pod 'SDWebImage', '~>3.8'
    pod 'MJRefresh', '3.1.0'
    pod 'MJExtension', '3.0.10'
    pod 'Masonry', '1.0.0'
    pod 'FDFullscreenPopGesture', '~> 1.1'
    pod 'ZFDownload', '~> 1.0.0'
    
    
    #  pod 'YTKNetwork'
    #  pod 'ReactiveCocoa','~>2.1.8'
    
end
